---
  version: "2"
  services:
    home-app:
      image: kallakukku/home-app:latest
      container_name: home-app
      restart: unless-stopped
      environment:
        - VUE_APP_POLLING_RATE=10000
        - VUE_APP_HUE_BRIDGE_IP=api.hue.mem-home.tk
        - VUE_APP_HUE_USERNAME=thKWqA-XrWM3yDocuuh3BurWImRDOZuUnL3cgCKa
        - VUE_APP_CALENDAR_API=https://api.caldav.mem-home.tk
        - VUE_APP_CALENDAR_UNAME=mem
        - VUE_APP_CALENDAR_PASS=kagemand
        - VUE_APP_WEATHER_API_KEY=ebe7fd78d568268d7e708e1cd4afebf6
      ports:
        - 8899:80
    home-app-api:
      image: kallakukku/home-app-api:latest
      container_name: home-app-api
      restart: unless-stopped
      ports:
        - 9988:3000